add datasource packet_project_ssh_key
packethost/terraform-provider-packet pull request #250
Opened 2020-08-28 05:32 UTC by displague

Implements #249 

Signed-off-by: Marques Johansson <marques@packet.com>

2020-08-28 20:32 UTC, t0mk commented
@displague I will take a look during the weekend or on Monday

2020-08-29 13:36 UTC, displague commented
The test isn't passing yet.

```
PACKNGO_DEBUG=1 TESTARGS="-run TestAccPacketProjectSSHKeyDataSource -count=1"  make testacc
```

2020-08-31 12:12 UTC, t0mk requested changes
Looks good overall, I just disagree with the `search` field. 

Also, think about uniting user and project keys in the datasource, it can save some code. I guess you've seen the `packet_ssh_key` resource.

2020-08-31 12:12 UTC, t0mk commented on packet/datasource_packet_project_ssh_key.go
> +		if testKey.Label == search || testKey.Key == search || testKey.ID == search || testKey.FingerPrint == search {
I think using general field (`search`) doesn't fit in the tf datasource concept. There should be concrete fields usable for search for those particular fields. I would limit the search for only
* `label` (no need to call it a `name`, it's `label` in Packet API)
* `fingerprint`

^ is the norm IIUC, see https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/account_ssh_key

I would drop
* search by `public_key` (can't think of a scenario where it would be useful). 
* search by `id`, which can be better used for `terraform import` I think. But I don't insist on this. If you keep search by ID, the field should be `project_ssh_key_id`.

2020-08-31 21:28 UTC, displague commented on packet/datasource_packet_project_ssh_key.go
> +		if testKey.Label == search || testKey.Key == search || testKey.ID == search || testKey.FingerPrint == search {
> label (no need to call it a name, it's label in Packet API)

I felt that way too, but in the Terraform provider the field is already being used as `name`, and not `label`.  I was trying to stay consistent to the Terraform provider.

> There should be concrete fields usable for search for those particular fields
I was taking advantage of an actual `search` query parameter provided by the API: _"Search by key, label, or fingerprint"_

I have a packngo PR that implements this with the API parameter: https://github.com/packethost/packngo/pull/190

To be faithful to the API and the eventual drop-in use of packethost/packngo#190, I should move `ID` to a separate datasource parameter.

>  If you keep search by ID, the field should be project_ssh_key_id.

I wanted to double-check this, I think the convention here is to match the field name. The AWS provider uses `id`, for example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eip (on many of the data sources). The GCP provider uses `something_id`.

> I think using general field (search) doesn't fit in the tf datasource concept

I think that depends on the capabilities of the provider, for example, this GCP datasource takes "filter" as a parameter:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/projects#example-usage---searching-for-projects-about-to-be-deleted-in-an-org














> search by public_key (can't think of a scenario where it would be useful).

👍  If I keep search, because it exists in the API, we won't need a separate `public_key`.  If we do need one, someone can request it.

2020-09-03 12:37 UTC, t0mk commented on packet/datasource_packet_project_ssh_key.go
> +		if testKey.Label == search || testKey.Key == search || testKey.ID == search || testKey.FingerPrint == search {
Makes sense with the ID attr naming, I'm always up for less text, but with these little things in TF, convention seems to be in the eye of the beholder:
https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/instance_image

.. I look at scaleway because they put a lot of effort in their TF provider, and I see it better align-fit to Packet than aws or gc. In effect, I don't care either way, but I would keep it consistent with the other datasoruces in the provider at a release time. I.e. let's change it either way, but for all DSs at a time. And maybe in a separate PR.

I wasn't aware about the `search` param in the API until yesterday. Why not wait till the packethost/packngo#190 PR is in and then drop fingerptint, public key and label, and only keep the ID.

I reallt don't see the point of `filter` once packethost/packngo#190 is in. You mean there would be 2 llayers of filtering, once in the API and then in TF provider?

2020-09-03 12:37 UTC, t0mk commented
I will check the test.

2020-09-03 13:15 UTC, t0mk commented on packet/datasource_packet_project_ssh_key_test.go
> +	keyName := acctest.RandomWithPrefix("tfacc-project-key")
maybe move this one line up, so that it's clear that the error check is for RansdSSHKeyPair

2020-09-03 13:17 UTC, t0mk commented on packet/datasource_packet_project_ssh_key_test.go
> +				ExpectError: regexp.MustCompile(keyName + " was not found"),
The test is failiing with 2 errors. First is

```
        errors during follow-up refresh: Project "788ede5c-35e0-4d2f-95db-21897a4e22ae" SSH Key matching "tfacc-project-key-1049025380679756230" was not found 0
        
        To match:
        
        tfacc-project-key-1049025380679756230 was not found
```

Because the regexp doesn't match the error. There's a double-quote char after the key ID.

The regexp should be `regexp.MustCompile(keyName + "\" was not found")`

2020-09-03 13:47 UTC, t0mk commented on packet/datasource_packet_project_ssh_key_test.go
> +				ExpectError: regexp.MustCompile(keyName + " was not found"),
[WIP]
I was not able to debug the other error, namely
```
inset error
```

The only fix I found to work was to separate the device removal 
```go
func testAccPacketProjectSSHKeyDataSourceConfig_noKey2(keyName string) string {
    config := fmt.Sprintf(`
data "packet_project_ssh_key" "foobar" {
    search = "%s"
    project_id = packet_project.test.id
}

resource "packet_project" "test" {
    name = "%s"
}`, keyName, keyName)
    return config
}

func TestAccPacketProjectSSHKeyDataSource_NoKey(t *testing.T) {
    keyName := acctest.RandomWithPrefix("tfacc-project-key")

    rekn := regexp.MustCompile(keyName + "\" was not found")

    resource.Test(t, resource.TestCase{
        PreCheck:     func() { testAccPreCheck(t) },
        Providers:    testAccProviders,
        //CheckDestroy: testAccCheckPacketSSHKeyDestroy,
        Steps: []resource.TestStep{
            {
                Config:      testAccPacketProjectSSHKeyDataSourceConfig_noKey1(keyName),
            },
            {
                Config:      testAccPacketProjectSSHKeyDataSourceConfig_noKey2(keyName),
                ExpectError:rekn,
            },
        },
    })
}

```

2020-09-03 14:22 UTC, displague commented on packet/datasource_packet_project_ssh_key.go
> +		if testKey.Label == search || testKey.Key == search || testKey.ID == search || testKey.FingerPrint == search {
I was only using Google's `filter` field as an example.  The Packet param would be called `search` to match the query parameter name that the Packet API uses. Yes, I do mean that there would be two layers, that the Terraform client would be implementing "search". If packethost/packngo#190 is merged first I will gladly remove the logic here.

2020-09-18 04:51 UTC, displague commented on packet/datasource_packet_project_ssh_key_test.go
> +				ExpectError: regexp.MustCompile(keyName + " was not found"),
https://github.com/terraform-providers/terraform-provider-aws/pull/7370 was the trick we needed here (an empty config following an errored config so that the destroy step will succeed).

I also added `PreventPostDestroyRefresh: true,` which may not be needed with the empty config trick.

The tests are passing now.

2020-09-21 08:28 UTC, t0mk approved these changes
The tests run. Good job fixing them.

2020-09-21 08:33 UTC, t0mk commented on packet/datasource_packet_project_ssh_key_test.go
> +				ExpectError: regexp.MustCompile(keyName + " was not found"),
PACKNGO_DEBUG=1 never worked for me in the provider testing, I've always been using TF_LOG=DEBUG to see the HTTP reqs/responses.

But I tried now with PACKNGO_DEBUG=1 and I didn't notice a delay.

I had troubles running the tests in the provider and in packngo when using go 1.15. I always had to switch to 1.13 (from go.mod of both of the projects), to test the code.

We should probably keep the Go version same in both of the projects.

2020-09-21 14:43 UTC, merged