Improved state removal and state removal logging
packethost/terraform-provider-packet pull request #268
Opened 2020-10-06 22:41 UTC by displague

Addresses https://github.com/packethost/terraform-provider-packet/issues/267

2020-10-07 08:25 UTC, t0mk commented on packet/resource_packet_spot_market_request.go
> +			log.Print("[WARN] SpotMarketRequest (%s) not found, removing from state", d.Id())
Should be Printf

from Checks:
`packet/resource_packet_spot_market_request.go:227: Print call has possible formatting directive %s`

2020-10-07 08:25 UTC, t0mk commented on packet/resource_packet_device_network_type.go
> +
I will test this later this afternoon, in the scenario of #267. If it goes well, I'll approve.

2020-10-07 08:29 UTC, invidian requested changes
Some nits. Will do functional tests later.

2020-10-07 08:29 UTC, invidian commented on packet/resource_packet_device.go
> +			log.Printf("[WARN] Device (%s) not found, removing from state", d.Id())
Should this line be followed by blank line for consistency with other changes?

2020-10-07 08:29 UTC, invidian commented on packet/resource_packet_device_network_type.go
> +
It's common in Go to not include this newline as far as I'm aware. Is there some linter which verifies it?

2020-10-07 08:29 UTC, invidian commented on packet/resource_packet_reserved_ip_block.go
> +			log.Printf("[WARN] Reserved IP Block (%s) not found, removing from state", d.Id())
Ditto newline consistency.

2020-10-07 08:29 UTC, invidian commented on go.sum
> -github.com/aws/aws-sdk-go v1.22.0 h1:e88V6+dSEyBibUy0ekOydtTfNWzqG3hrtCR8SF6UqqY=
Seems like a implicit dependency update. Should this be committed separately?

2020-10-07 10:32 UTC, t0mk commented
@displague ah, the acceptance tests don't run because of the Packngo update. The Equinix endpoint doesn't work well yet. Reported in #269. 

Maybe move the packngo update (With the new endpoint) to a different PR.

2020-10-07 12:45 UTC, invidian approved these changes
Functionality wise also looks good to me! :+1: Thanks for improving it @displague.

Would be nice to have acceptance tests for it too :smile:

2020-10-07 14:26 UTC, displague commented on GNUmakefile
> +	go test $(TEST) || exit 1
I noted this in the git commit, but https://github.com/golang/go/issues/37962#issuecomment-602664676 is justification for this. I could not run `make test` on my Mac because of `-i`. `make test` is useful for finding the linting problems that I overlooked previously.

2020-10-08 07:52 UTC, t0mk commented
@displague thanks for removing the packngo update. I am now testing - I run couple of acc tests that pass, and I am now checking the scenario of #267 manually

2020-10-08 07:56 UTC, t0mk approved these changes

2020-10-08 13:59 UTC, merged